name: List Docker images
description: Generates lists of docker images for repo in desired formats

inputs:
  tag:
    default: ${{ github.ref_name }}
    description: Tag to use for full image names
  include-base-image:
    default: false
    type: boolean
    description: Flag to include the node base image to the list

outputs:
  matrix:
    description: Array of objects each containing the image's dockerfile, short name, and full name

runs:
  using: node20
  main: index.js