name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      prod-release:
        description: True if this is initiated from a production release
        required: false
        default: false
        type: boolean
      app-version:
        description: App version value
        required: false
        type: string
jobs:
  test:
    name: Test inputs
    runs-on: ubuntu-22.04
    steps:
    - name: Check app-version
      run: |
        if [[ "${{ github.event.inputs.prod-release }}" == "false" && (-z "${{ github.event.inputs.app-version }}" || "${{ github.event.inputs.app-version }}" == "null") ]]; then
          echo "TAG=test-image:latest"
        else
          echo "TAG=test-image:${{ github.event.inputs.app-version }}"
        fi
        echo "$TAG"




