name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  build-test-images:
    name: Build and Test Images
    uses: ./.github/workflows/workflow1.yaml
    secrets: inherit