name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  print-variable:
    name: Print App Version
    strategy:
      matrix:
        env:
          - dev
          - qa
          - sandbox
          - prod
    runs-on: ubuntu-latest
    steps:
      - name: Determine Bucket
        if: ${{ vars.IS_APP_DEPRECATED && matrix.env != 'prod' }}
        run: |
          if [ "${{ vars.IS_APP_DEPRECATED }}" == "true" ]; then
            echo "value=s3://codeva-techdocs-storage-${{ matrix.env }}"
          else
            echo "value=s3://embark-techdocs-storage-${{ matrix.env == 'prod' && 'prod' || 'nonprod' }}"
          fi
        shell: bash