name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  print-variable:
    name: Print App Version
    strategy:
      matrix:
        env:
          - qa
          - prod
    runs-on: ubuntu-latest
    steps:
      - name: Use ArgoCD bucket
        if: ${{ vars.IS_APP_DEPRECATED }}
        run: |
          echo ${{ vars.IS_APP_DEPRECATED }}
          echo echo "value=s3://codeva-techdocs-storage-${{ matrix.env == 'prod' && 'prod' || 'nonprod' }}"
        shell: bash
      - name: Use non ArgoCD bucket
        if: ${{ vars.IS_APP_DEPRECATED }}
        run: |
          echo ${{ vars.IS_APP_DEPRECATED }}
          echo echo "value=s3://embark-techdocs-storage-${{ matrix.env == 'prod' && 'prod' || 'nonprod' }}"
        shell: bash
