name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  # Unfortunately, we can't reuse a workflow in a composite actions
  # So we have to use this hideaous workaround
  determine-deprecation:
    name: Print App Version
    strategy:
      matrix:
        env:
          - dev
          - qa
          - sandbox
          - prod
        enable-prod:
          - ${{ vars.IS_APP_DEPRECATED }}
        exclude:
          - env: prod
            enable-prod: 'true'
    outputs:
      dev: ${{ steps.determine-app-deprecated.outputs.dev }}
      qa: ${{ steps.determine-app-deprecated.outputs.qa }}
      sandbox: ${{ steps.determine-app-deprecated.outputs.sandbox }}
      prod: ${{ steps.determine-app-deprecated.outputs.prod }}
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    steps:
      - name: Determine App Deprecated Value
        id: determine-app-deprecated
        run: |
          echo "${{ matrix.env }}=${{ vars.IS_APP_DEPRECATED }}" >> $GITHUB_OUTPUT
          echo "${{ matrix.env }}=${{ vars.IS_APP_DEPRECATED }}"

  print-value:
    name: Print Value
    runs-on: ubuntu-latest
    needs: determine-deprecation
    strategy:
      matrix:
        env:
          - dev
          - qa
          - sandbox
          - prod
        enable-prod:
          - ${{ vars.IS_APP_DEPRECATED }}
        exclude:
          - env: prod
            enable-prod: 'true'
    steps:
      - name: Print
        run: echo  "${{ fromJson(needs.determine-deprecation.outputs[matrix.env]) }}"

  # print-value:
  #   name: Print Value
  #   runs-on: ubuntu-latest
  #   needs: determine-deprecation
  #   steps:
  #     - name: Print
  #       run: |
  #         echo "dev: ${{ needs.determine-deprecation.outputs.dev }}"
  #         echo "qa: ${{ needs.determine-deprecation.outputs.qa }}"
  #         echo "sandbox: ${{ needs.determine-deprecation.outputs.sandbox }}"
