name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  print-variable:
    name: Print App Version
    strategy:
      matrix:
        env:
          - dev
          - qa
          - sandbox
          - prod
        enable-prod:
          - ${{ vars.IS_APP_DEPRECATED }}
        exclude:
          - env: prod
            enable-prod: 'true'
    runs-on: ubuntu-latest
    environment: ${{ matrix.env}}
    steps:
      - name: Print environment value
        run: echo "{{ vars.IS_APP_DEPRECATED }}"
        shell: bash