name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  create-json:
    runs-on: ubuntu-latest
    outputs:
      json-output: ${{ steps.create-json.outputs.json }}
    steps:
      - name: Generate JSON Object
        id: create-json
        run: |
          echo '{"message": "Hello from the first job!", "value": 42}' >> GITHUB_OUTPUT
        shell: bash

  use-json:
    needs: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Print JSON from First Job
        run: |
          echo "Received JSON: ${{ needs.create-json.outputs.json-output }}"
