name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      prod-release:
        description: True if this is initiated from a production release
        required: false
        default: false
        type: boolean
      app-version:
        description: App version value
        default: 'latest'
        required: false
        type: string
jobs:
  test:
    name: Test inputs
    runs-on: ubuntu-22.04
    steps:
    - name: Check app-version
      run: |
        echo ${{ format('test-image:{0}', ( inputs.prod-release && 'latest' ) || inputs.app-version)  }}




