name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  get-images-list:
    name: Get images list
    runs-on: ubuntu-22.04
    outputs:
      matrix: ${{ steps.images-list.outputs.matrix }}
      services: ${{ steps.images-list.outputs.services }}
      tagged-images: ${{ steps.images-list.outputs.json-array }}
    steps:
      - uses: actions/checkout@v4
      - name: Get images list
        uses: ./.github/actions/get-images-list
        id: images-list
        with:
          include-base-image: true

  build-base-node-image:
    needs: [get-images-list]
    name: Build Base Node Image
    uses: ./.github/workflows/workflow1.yaml
    with:
      image: node-base
    secrets: inherit

  build-images:
    name: Build Application Images
    needs: [get-images-list, build-base-node-image]
    strategy:
      matrix:
        service-name: ${{ fromJSON(needs.get-service-names.outputs.services-array) }}
    uses: ./.github/workflows/workflow1.yaml
    with:
      image: ${{ matrix.service-name }}
    secrets: inherit


  # print-service-names:
  #   runs-on: ubuntu-latest
  #   needs: [get-images-list]
  #   strategy:
  #     matrix:
  #       service-name: ${{ fromJSON(needs.get-images-list.outputs.services) }}
  #   name: Build ${{ matrix.service-name }} image
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #     - name: Display Service Name
  #       id: display
  #       run: |
  #         echo "service : ${{ matrix.service-name }}"

  # print-image-names:
  #   runs-on: ubuntu-latest
  #   needs: [get-images-list]
  #   strategy:
  #     matrix:
  #       include: ${{ fromJSON(needs.get-images-list.outputs.matrix) }}
  #   name: Build ${{ matrix.service-name }} image
  #   steps:
  #     - name: Check out repo
  #       uses: actions/checkout@v4
  #     - name: Display Image Name
  #       id: display
  #       run: |
  #         echo "Image : ${{ matrix.service-name }}"
  #         echo "Image : ${{ matrix.ghcr-name }}"


