name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      prod-release:
        description: True if this is initiated from a production release
        required: false
        default: false
        type: boolean
      app-version:
        description: App version value
        required: false
        type: string
jobs:
  test:
    name: Test inputs
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.check_version.outputs.value }} # Define the output for the job
    steps:
      - name: Check app-version
        id: check_version
        run: |
          if [[ -z "${{ github.event.inputs.app-version }}" || "${{ github.event.inputs.app-version }}" == "null" ]] && \
             [[ -z "${{ github.event.inputs.prod-release }}" || "${{ github.event.inputs.prod-release }}" == "false" || "${{ github.event.inputs.prod-release }}" == "null" ]]; then
            echo "value=latest" >> $GITHUB_OUTPUT
          else
            if [[ "${{ github.event.inputs.prod-release }}" == "true" ]]; then
              echo "value=latest" >> $GITHUB_OUTPUT
            else
              echo "value=${{ github.event.inputs.app-version }}" >> $GITHUB_OUTPUT
            fi
          fi
      - name: Use the output
        run: |
          echo "The app version is ${{ steps.check_version.outputs.value }}"
