name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  create-json:
    runs-on: ubuntu-latest
    outputs:
      json-output: ${{ steps.create-json.outputs.json }}
    steps:
      - name: Generate JSON Object
        id: create-json
        run: |
          echo 'json=[{"image": "ghcr.io/department-of-veterans-affairs/code-va/self-hosted-runner-e2e:edge", "signed": false}, {"image": "ghcr.io/department-of-veterans-affairs/code-va/runner-base:edge", "signed": true}, {"image": "ghcr.io/department-of-veterans-affairs/code-va/node-base:edge", "signed": true}, {"image": "ghcr.io/department-of-veterans-affairs/code-va/frontend:edge", "signed": true}, {"image": "ghcr.io/department-of-veterans-affairs/code-va/backend:edge", "signed": false}]' >> "$GITHUB_OUTPUT"
        shell: bash

  use-json:
    needs: create-json
    runs-on: ubuntu-latest
    steps:
      - name: Print JSON from First Job
        run: |
          echo ${{ fromJSON(needs.create-json.outputs.json-output) | jq '[.[] | select(.signed == true)]' }}
