name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  print-variable:
    name: Print App Version
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo ${{ vars.MY_REPO_VAR }}
        shell: bash
