name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  get-app-version:
    uses: ./.github/workflows/get-app-version.yaml

  test:
    name: Test app-version
    needs: [get-app-version]
    uses: ./.github/workflows/workflow1.yaml
    with:
      app-version: "version1"

