name: Continuous Integration (CI)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:

  print-variable:
    name: Print App Version
    strategy:
      matrix:
        env:
          - dev
          - qa
          - sandbox
        enable-prod: ${{ vars.IS_APP_DEPRECATED }}
        include:
          - env: prod
            enable-prod: ${{ vars.IS_APP_DEPRECATED == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine Bucket
        run: echo "value=s3://codeva-techdocs-storage-${{ matrix.env }}"
        shell: bash