name: Build, Test, Scan, Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Select the image'
        required: true
        type: choice
        options:
          - base-node-image
          - frontend
          - backend
          - postgresql
          - memcached
  workflow_call:
    inputs:
      image:
        default: 'frontend'
        description: True if should force build, else only if changed files on this ref
        type: string
        required: true
jobs:
  get-image-details:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-build-parameters.outputs.matrix }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up for node GH Actions
      uses: ./.github/actions/setup-node-actions

    - name: Get image build parameter details
      id: get-build-parameters
      uses: ./.github/actions/get-image-details
      with:
        name: ${{ inputs.image}}

  build:
    runs-on: ubuntu-latest
    needs: [get-image-details]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Parse Image Details
      id: parse-json
      run: |
        echo "Deploying to ${{ fromJSON(needs.get-image-details.outputs.matrix).service-name }}"
        echo "Deploying to ${{ fromJSON(needs.get-image-details.outputs.matrix).docker-file-path }}"

  build-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service-name: [frontend, backend, postgres]

    name: Build ${{ matrix.service-name }} image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          # To compute dirty files need fetch-depth=2 to grab previous commit on it
          fetch-depth: 2
      - name: Display Service Name
        id: display
        run: |
          echo "Deploying to ${{ matrix.service-name }}"
          echo "Deploying to ${{ matrix.service-name }}"