name: Build, Test, Scan, Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Select the image'
        required: true
        type: choice
        options:
          - base-node-image
          - frontend
          - backend
          - postgresql
          - memcached
  workflow_call:
    inputs:
      image:
        default: 'frontend'
        description: True if should force build, else only if changed files on this ref
        type: string
        required: true
jobs:
  get-image-details:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.get-build-parameters.outputs.matrix }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up for node GH Actions
      uses: ./.github/actions/setup-node-actions

    - name: Get image build parameter details
      id: get-build-parameters
      uses: ./.github/actions/get-image-details
      with:
        name: frontend

  build:
    runs-on: ubuntu-latest
    needs: [get-image-details]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Deploying to ${{ needs.get-image-details.outputs.matrix.service-name }}"
        echo "Deploying to ${{ needs.get-image-details.outputs.matrix.docker-file-path }}"