name: Build, Test, Scan, Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Select the image'
        required: true
        type: choice
        options:
          - base-node-image
          - frontend
          - backend
  workflow_call:
    inputs:
      image:
        description: 'Select the image'
        required: true
        type: choice
        options:
          - base-node-image
          - frontend
          - backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Deploying to ${{ inputs.image }}"
