name: Build, Test, Scan, Image

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Select the image'
        required: true
        type: choice
        options:
          - base-node-image
          - frontend
          - backend
  workflow_call:
    inputs:
      image:
        default: 'base-node-image'
        description: True if should force build, else only if changed files on this ref
        type: string
        required: true
jobs:
  get-image-details:
    runs-on: ubuntu-latest
    steps:
    - name: Set up for node GH Actions
      uses: ./.github/actions/setup-node-actions

    - name: Get image build parameter details
      uses: ./.github/actions/get-image-details
      with:
        name: frontend

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Deploying to ${{ inputs.image }}"
