name: Workflow with Options

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      feature:
        description: 'Select the feature to deploy'
        required: false
        type: choice
        options:
          - feature1
          - feature2
          - feature3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Run a script
      run: |
        echo "Deploying to ${{ github.event.inputs.environment }}"
        echo "Feature selected: ${{ github.event.inputs.feature }}"